# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: judge.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='judge.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bjudge.proto\x1a\x1bgoogle/protobuf/empty.proto\"7\n\x0cJudgeRequest\x12\x11\n\tjudger_id\x18\x01 \x01(\t\x12\x14\n\x0cjudger_token\x18\x02 \x01(\t\"7\n\x0f\x46\x65tchTaskResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x04task\x18\x02 \x01(\x0b\x32\x05.Task\"L\n\x04Task\x12\x10\n\x08task_tag\x18\x01 \x01(\x03\x12\x12\n\nproblem_id\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x0c\n\x04\x63ode\x18\x04 \x01(\t\"\x0e\n\x0cTaskProgress\"=\n\nTaskResult\x12\x10\n\x08task_tag\x18\x01 \x01(\x03\x12\x0e\n\x06result\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x02\x32\xad\x01\n\x05Judge\x12.\n\tFetchTask\x12\r.JudgeRequest\x1a\x10.FetchTaskResult\"\x00\x12<\n\x0fSetTaskProgress\x12\r.TaskProgress\x1a\x16.google.protobuf.Empty\"\x00(\x01\x12\x36\n\rSetTaskResult\x12\x0b.TaskResult\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_JUDGEREQUEST = _descriptor.Descriptor(
  name='JudgeRequest',
  full_name='JudgeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='judger_id', full_name='JudgeRequest.judger_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='judger_token', full_name='JudgeRequest.judger_token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=99,
)


_FETCHTASKRESULT = _descriptor.Descriptor(
  name='FetchTaskResult',
  full_name='FetchTaskResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='FetchTaskResult.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='task', full_name='FetchTaskResult.task', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=156,
)


_TASK = _descriptor.Descriptor(
  name='Task',
  full_name='Task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_tag', full_name='Task.task_tag', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='problem_id', full_name='Task.problem_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='language', full_name='Task.language', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='Task.code', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=234,
)


_TASKPROGRESS = _descriptor.Descriptor(
  name='TaskProgress',
  full_name='TaskProgress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=250,
)


_TASKRESULT = _descriptor.Descriptor(
  name='TaskResult',
  full_name='TaskResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_tag', full_name='TaskResult.task_tag', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='TaskResult.result', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='TaskResult.score', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=313,
)

_FETCHTASKRESULT.fields_by_name['task'].message_type = _TASK
DESCRIPTOR.message_types_by_name['JudgeRequest'] = _JUDGEREQUEST
DESCRIPTOR.message_types_by_name['FetchTaskResult'] = _FETCHTASKRESULT
DESCRIPTOR.message_types_by_name['Task'] = _TASK
DESCRIPTOR.message_types_by_name['TaskProgress'] = _TASKPROGRESS
DESCRIPTOR.message_types_by_name['TaskResult'] = _TASKRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JudgeRequest = _reflection.GeneratedProtocolMessageType('JudgeRequest', (_message.Message,), dict(
  DESCRIPTOR = _JUDGEREQUEST,
  __module__ = 'judge_pb2'
  # @@protoc_insertion_point(class_scope:JudgeRequest)
  ))
_sym_db.RegisterMessage(JudgeRequest)

FetchTaskResult = _reflection.GeneratedProtocolMessageType('FetchTaskResult', (_message.Message,), dict(
  DESCRIPTOR = _FETCHTASKRESULT,
  __module__ = 'judge_pb2'
  # @@protoc_insertion_point(class_scope:FetchTaskResult)
  ))
_sym_db.RegisterMessage(FetchTaskResult)

Task = _reflection.GeneratedProtocolMessageType('Task', (_message.Message,), dict(
  DESCRIPTOR = _TASK,
  __module__ = 'judge_pb2'
  # @@protoc_insertion_point(class_scope:Task)
  ))
_sym_db.RegisterMessage(Task)

TaskProgress = _reflection.GeneratedProtocolMessageType('TaskProgress', (_message.Message,), dict(
  DESCRIPTOR = _TASKPROGRESS,
  __module__ = 'judge_pb2'
  # @@protoc_insertion_point(class_scope:TaskProgress)
  ))
_sym_db.RegisterMessage(TaskProgress)

TaskResult = _reflection.GeneratedProtocolMessageType('TaskResult', (_message.Message,), dict(
  DESCRIPTOR = _TASKRESULT,
  __module__ = 'judge_pb2'
  # @@protoc_insertion_point(class_scope:TaskResult)
  ))
_sym_db.RegisterMessage(TaskResult)



_JUDGE = _descriptor.ServiceDescriptor(
  name='Judge',
  full_name='Judge',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=316,
  serialized_end=489,
  methods=[
  _descriptor.MethodDescriptor(
    name='FetchTask',
    full_name='Judge.FetchTask',
    index=0,
    containing_service=None,
    input_type=_JUDGEREQUEST,
    output_type=_FETCHTASKRESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetTaskProgress',
    full_name='Judge.SetTaskProgress',
    index=1,
    containing_service=None,
    input_type=_TASKPROGRESS,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetTaskResult',
    full_name='Judge.SetTaskResult',
    index=2,
    containing_service=None,
    input_type=_TASKRESULT,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_JUDGE)

DESCRIPTOR.services_by_name['Judge'] = _JUDGE

# @@protoc_insertion_point(module_scope)
