# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: primitive.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='primitive.proto',
  package='syzoj.primitive',
  syntax='proto2',
  serialized_options=_b('Z&github.com/syzoj/syzoj-ng-go/app/model'),
  serialized_pb=_b('\n\x0fprimitive.proto\x12\x0fsyzoj.primitive\"\x16\n\x08ObjectID\x12\n\n\x02id\x18\x01 \x02(\tB(Z&github.com/syzoj/syzoj-ng-go/app/model')
)




_OBJECTID = _descriptor.Descriptor(
  name='ObjectID',
  full_name='syzoj.primitive.ObjectID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='syzoj.primitive.ObjectID.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=58,
)

DESCRIPTOR.message_types_by_name['ObjectID'] = _OBJECTID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ObjectID = _reflection.GeneratedProtocolMessageType('ObjectID', (_message.Message,), dict(
  DESCRIPTOR = _OBJECTID,
  __module__ = 'primitive_pb2'
  # @@protoc_insertion_point(class_scope:syzoj.primitive.ObjectID)
  ))
_sym_db.RegisterMessage(ObjectID)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
