# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tagger.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tagger.proto',
  package='tagger',
  syntax='proto3',
  serialized_options=_b('Z1github.com/amsokol/protoc-gen-gotag/tagger;tagger'),
  serialized_pb=_b('\n\x0ctagger.proto\x12\x06tagger\x1a google/protobuf/descriptor.proto:-\n\x04tags\x12\x1d.google.protobuf.FieldOptions\x18\xc3\xe0\x33 \x01(\t:3\n\noneof_tags\x12\x1d.google.protobuf.OneofOptions\x18\xc3\xe0\x33 \x01(\tB3Z1github.com/amsokol/protoc-gen-gotag/tagger;taggerb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])


TAGS_FIELD_NUMBER = 847939
tags = _descriptor.FieldDescriptor(
  name='tags', full_name='tagger.tags', index=0,
  number=847939, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=_b("").decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)
ONEOF_TAGS_FIELD_NUMBER = 847939
oneof_tags = _descriptor.FieldDescriptor(
  name='oneof_tags', full_name='tagger.oneof_tags', index=1,
  number=847939, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=_b("").decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)

DESCRIPTOR.extensions_by_name['tags'] = tags
DESCRIPTOR.extensions_by_name['oneof_tags'] = oneof_tags
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(tags)
google_dot_protobuf_dot_descriptor__pb2.OneofOptions.RegisterExtension(oneof_tags)

DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
